export const MAP_PNG_ARR = [
  [
    'https://drive.google.com/u/1/uc?id=1uzuTvg7c0vG1gJU3qBinMVlK8PeL1-uU&export=download',
    'https://drive.google.com/u/1/uc?id=1RIbtZrfXhaIOHoUXNb0P7tGANwTaaskL&export=download',
    'https://drive.google.com/u/1/uc?id=15MjX6kAsO2WNudmzurEIdL-h39afuAwM&export=download',
    'https://drive.google.com/u/1/uc?id=1PTI6-AJIRDYijOWtm32J16QIXapJdDYf&export=download',
    'https://drive.google.com/u/1/uc?id=1TH1Y9gTURT9l6lfMOs2EfMQdiB99pW3k&export=download',
    'https://drive.google.com/u/1/uc?id=1NzH6rz6_P5winQf3tDG7w4NJEzgghnOo&export=download',
    'https://drive.google.com/u/1/uc?id=1kEppU6KBtzGSM0HMDpL-fY9JRMLmZG7u&export=download',
    'https://drive.google.com/u/1/uc?id=1tOg3M5w5MLbDWtG9xg85cvHAE4QYzMDc&export=download',
  ],
  [
    'https://drive.google.com/u/1/uc?id=1Mg1BmeDRl8NrnFomKB_48wsH_m-l47Av&export=download',
    'https://drive.google.com/u/1/uc?id=1QlqHt7a1KMNSsPT1naYWU6nHkcRWnRYK&export=download',
    'https://drive.google.com/u/1/uc?id=1V-RHp5csEIr0v-2CF7y6JPrrw2865mMP&export=download',
    'https://drive.google.com/u/1/uc?id=1XiivnTm3QJgnMXfmXyhIldwzc9U48BgE&export=download',
    'https://drive.google.com/u/1/uc?id=1gYKifvhHamx3QC6O9KCApXqUhPqP4C1l&export=download',
    'https://drive.google.com/u/1/uc?id=1m-pRDUk7OHgW21NfHuQtmjmcYxtXG2AN&export=download',
    'https://drive.google.com/u/1/uc?id=1niQ0MA9NfAq7wQJd0CHRwPxnQBCiFH9z&export=download',
    'https://drive.google.com/u/1/uc?id=1uFNvjacSVtU3YzyBFhAH5aV6Zbl01zkf&export=download',
  ],
  [
    'https://drive.google.com/u/1/uc?id=1AnVpXF-eMbAf1FkglL1dzpt-TJ9ahfly&export=download',
    'https://drive.google.com/u/1/uc?id=1CqiEgl5hxaWF4CUv4j6-5dRS13tSvcWB&export=download',
    'https://drive.google.com/u/1/uc?id=1EcwaaU2OEpuphzwtFjuEHtn9TqnPaCm2&export=download',
    'https://drive.google.com/u/1/uc?id=1FOea4CyRM862pxXXpTcF6kmutq3yUgxb&export=download',
    'https://drive.google.com/u/1/uc?id=1TU7zPzXLqXbsA6qXpIWGkTAgyZMOE_PG&export=download',
    'https://drive.google.com/u/1/uc?id=1VfGXxCjOfIP0NEnMxUsX82Av6_U6yiF1&export=download',
    'https://drive.google.com/u/1/uc?id=1YRFSdRuu8w7nYyOfblQBbyRq8TsvRoJn&export=download',
    'https://drive.google.com/u/1/uc?id=1YUiyod7gN-EM631vMnK0b0OXUrUvNMkv&export=download',
  ],
  [
    'https://drive.google.com/u/1/uc?id=16moMQoxD3lN_4w5w_4I09GqAMiserCq5&export=download',
    'https://drive.google.com/u/1/uc?id=16tn1buvXrpZqX11huXMA50wr7jG5krlk&export=download',
    'https://drive.google.com/u/1/uc?id=1HEeBsKy09k1ISFmtRTEahvLrwl5n13uP&export=download',
    'https://drive.google.com/u/1/uc?id=1IBQJ0-9fiQOiHAyRRqyRH3dgxUIqi9wT&export=download',
    'https://drive.google.com/u/1/uc?id=1aIyUEbdSwsDkJndccffD_ve5L5SN5F7-W&export=download',
    'https://drive.google.com/u/1/uc?id=1g2iYBDiteS7dhMdgYIusg9S7hD-3k40i&export=download',
    'https://drive.google.com/u/1/uc?id=1h478bwqwRyicS17UKLXGvVi083qhDzQW&export=download',
    'https://drive.google.com/u/1/uc?id=1u9sERNAjh0gRKugDFDiSXO4BUesgQvZQ&export=download',
  ],
  [
    'https://drive.google.com/u/1/uc?id=17LRHNxawf66feu0Tfb4bns54tgH28G9o&export=download',
    'https://drive.google.com/u/1/uc?id=1EB_Pkh90kLEPgrOYvqodsxKgXboGjOcC&export=download',
    'https://drive.google.com/u/1/uc?id=1P4115zWTd08kH6B387w35syft7sC0muW&export=download',
    'https://drive.google.com/u/1/uc?id=1TTIw35BLulODQfM_Z7PkL58yKq9GGR9x&export=download',
    'https://drive.google.com/u/1/uc?id=1Y84u12g2nRXWN6FP_86GvziCSoHWUd0S&export=download',
    'https://drive.google.com/u/1/uc?id=1YG9I5slr44-fzeFIkWNbM12FS8iUaCYu&export=download',
    'https://drive.google.com/u/1/uc?id=1hsuOtROGgf1MSpQZcf605RbQ46IwPGi8&export=download',
    'https://drive.google.com/u/1/uc?id=1zRsf2MGFfyz1aE8t4SQVy092fqIcwUQ6&export=download',
  ],
  [
    'https://drive.google.com/u/1/uc?id=17Ei5bhmeU3fpsV1WvUOnTgPA372o3cJf&export=download',
    'https://drive.google.com/u/1/uc?id=1CNa4NP8EvuSbORLPU1hX-xAq7g4uiRpb&export=download',
    'https://drive.google.com/u/1/uc?id=1D5WQ5BqyYMbwtWi63buz3qA9RfmjV72r&export=download',
    'https://drive.google.com/u/1/uc?id=1GtvGfslE19EjZf50IEpF3-HDQQrrmUvI&export=download',
    'https://drive.google.com/u/1/uc?id=1Qwvv0VtgRj2NGrVuljxh6IZsvIJ9Dec9&export=download',
    'https://drive.google.com/u/1/uc?id=1S3YOB0qwcPJXTYjnaApwDhcB4hTx4ZSA&export=download',
    'https://drive.google.com/u/1/uc?id=1wZABKjTm8XKgTJZZVDyBkaJCFfoACV1f&export=download',
    'https://drive.google.com/u/1/uc?id=1xu81HgOhgQB0xGHvLK4lm0UgaeYmjsXo&export=download',
  ],
  [
    'https://drive.google.com/u/1/uc?id=18r8kPd2IjFARywEL4XxAIeRdSsloqAvm&export=download',
    'https://drive.google.com/u/1/uc?id=1CaIIutbWn81MZ4GrW2P8vcFLQRisxAcp&export=download',
    'https://drive.google.com/u/1/uc?id=1H175XzmgFB0x9b_I5bu6fdTe6PuBKiey&export=download',
    'https://drive.google.com/u/1/uc?id=1PvpIdLzshF3WFCQ3zJPLNu9ETYKQ5rjR&export=download',
    'https://drive.google.com/u/1/uc?id=1Wv1hyAkuJszt9lcYMzprZcQhyVuaZZoJ9&export=download',
    'https://drive.google.com/u/1/uc?id=1tOEQnM5-CPqrY3xxM9u53AKPQInwjl13&export=download',
    'https://drive.google.com/u/1/uc?id=1u3kzGKP7pfmp95mKzQ6CPcjJROdbWuQt&export=download',
    'https://drive.google.com/u/1/uc?id=1xgV69PFUKSuc3M6-O-pSms61V_C5inud&export=download',
  ],
  [
    'https://drive.google.com/u/1/uc?id=11XDtflu6bBWxHu_iTwgyhJk9dh1N0Fkf&export=download',
    'https://drive.google.com/u/1/uc?id=146gb2ZGFQ3b0Wwu0jYc_NTuSV8mjeQZC&export=download',
    'https://drive.google.com/u/1/uc?id=1QGD4OzHcrNB_DDiw8Lgtl5FAIQWqczmJ&export=download',
    'https://drive.google.com/u/1/uc?id=1VEq_9RkQovF0Lxq_C6_8CEWRaZt62D_1&export=download',
    'https://drive.google.com/u/1/uc?id=1lPelRhWqJQVQ5roAalNpOKuSDe6ek-39&export=download',
    'https://drive.google.com/u/1/uc?id=1laqF34j6gL_P1HS4hfZzlvhsxI1zOeS-&export=download',
    'https://drive.google.com/u/1/uc?id=1sFZ4jslxLsuCKnP4D5UbQZIhsreseR8M&export=download',
    'https://drive.google.com/u/1/uc?id=1wZDeoc_bM977hl50T-9ZpN85X0VHCbGA&export=download',
  ],
];

export const MOUSE_ICONS = {
  GRAB: process.env.PUBLIC_URL + '/icons/svg/grab-icon.svg',
  DEFAULT: process.env.PUBLIC_URL + '/icons/svg/cursor-icon.svg',
};
export const MAP_MOUSE_MODES = {
  SELECT: 'default',
  DRAG: 'grab',
  DRAG_ACTIVE: '',
};
