// Alert
export const ALERT_TYPES = {
  SET_ALERT: 'SET_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT',
};

// Auth
export const AUTH_TYPES = {
  LOGIN: 'LOGIN',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  REGISTER: 'REGISTER',
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_ERROR: 'REGISTER_ERROR',
};

// User
export const USER_TYPES = {
  GET_USER: 'GET_USER',
  GET_USER_REQUEST: 'GET_USER_REQUEST',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_ERROR: 'GET_USER_ERROR',
  CLEAR_USER: 'CLEAR_USER',
};

export const MAP_INTERACTIONS_TYPES = {
  SHOW_DATA: 'SHOW_DATA',
  HIDE_DATA: 'HIDE_DATA',
  GET_COUNTRY: 'GET_COUNTRY',
  GET_COUNTRY_REQUEST: 'GET_COUNTRY_REQUEST',
  GET_COUNTRY_SUCCESS: 'GET_COUNTRY_SUCCESS',
  GET_COUNTRY_ERROR: 'GET_COUNTRY_ERROR',
  CREATE_COUNTRY: 'CREATE_COUNTRY',
  CREATE_COUNTRY_REQUEST: 'CREATE_COUNTRY_REQUEST',
  CREATE_COUNTRY_SUCCESS: 'CREATE_COUNTRY_SUCCESS',
  CREATE_COUNTRY_ERROR: 'CREATE_COUNTRY_ERROR',
  UPDATE_COUNTRY: 'UPDATE_COUNTRY',
  UPDATE_COUNTRY_REQUEST: 'UPDATE_COUNTRY_REQUEST',
  UPDATE_COUNTRY_SUCCESS: 'UPDATE_COUNTRY_SUCCESS',
  UPDATE_COUNTRY_ERROR: 'UPDATE_COUNTRY_ERROR',
  DELETE_COUNTRY: 'DELETE_COUNTRY',
  DELETE_COUNTRY_REQUEST: 'DELETE_COUNTRY_REQUEST',
  DELETE_COUNTRY_SUCCESS: 'DELETE_COUNTRY_SUCCESS',
  DELETE_COUNTRY_ERROR: 'DELETE_COUNTRY_ERROR',
};

export const TAGS_EDITOR_TYPES = {
  SELECT_TAG: 'SELECT_TAG',
  GET_ALL_TAGS: 'GET_ALL_TAGS',
  GET_ALL_TAGS_REQUEST: 'GET_ALL_TAGS_REQUEST',
  GET_ALL_TAGS_SUCCESS: 'GET_ALL_TAGS_SUCCESS',
  GET_ALL_TAGS_ERROR: 'GET_ALL_TAGS_ERROR',
  CREATE_TAG: 'CREATE_TAG',
  CREATE_TAG_REQUEST: 'CREATE_TAG_REQUEST',
  CREATE_TAG_SUCCESS: 'CREATE_TAG_SUCCESS',
  CREATE_TAG_ERROR: 'CREATE_TAG_ERROR',
  UPDATE_TAG: 'UPDATE_TAG',
  UPDATE_TAG_REQUEST: 'UPDATE_TAG_REQUEST',
  UPDATE_TAG_SUCCESS: 'UPDATE_TAG_SUCCESS',
  UPDATE_TAG_ERROR: 'UPDATE_TAG_ERROR',
  DELETE_TAG: 'DELETE_TAG',
  DELETE_TAG_REQUEST: 'DELETE_TAG_REQUEST',
  DELETE_TAG_SUCCESS: 'DELETE_TAG_SUCCESS',
  DELETE_TAG_ERROR: 'DELETE_TAG_ERROR',
};
