// Alert
export const ALERT_TYPES = {
  SET_ALERT: 'SET_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT',
};

// Auth
export const AUTH_TYPES = {
  LOGIN: 'LOGIN',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  REGISTER: 'REGISTER',
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_ERROR: 'REGISTER_ERROR',
};

// User
export const USER_TYPES = {
  GET_USER: 'GET_USER',
  GET_USER_REQUEST: 'GET_USER_REQUEST',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_ERROR: 'GET_USER_ERROR',
  CLEAR_USER: 'CLEAR_USER',
};

export const MAP_INTERACTIONS_TYPES = {
  SHOW_DATA: 'SHOW_DATA',
  HIDE_DATA: 'HIDE_DATA',
  GET_COUNTRY: 'GET_COUNTRY',
  GET_COUNTRY_REQUEST: 'GET_COUNTRY_REQUEST',
  GET_COUNTRY_SUCCESS: 'GET_COUNTRY_SUCCESS',
  GET_COUNTRY_ERROR: 'GET_COUNTRY_ERROR',
};